name: Mirror to Tangled

on: [push, delete]

jobs:
    mirror:
        runs-on: blacksmith-2vcpu-ubuntu-2404
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pixta-dev/repository-mirroring-action@v1
              with:
                  target_repo_url: git@tangled.org:pvzm.net/docs
                  ssh_private_key: ${{ secrets.TANGLED_SSH_PRIVATE_KEY }}
